# -*- coding: utf-8 -*-
"""협업 필터링 모델 (1)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TRkYT-CVt0s2f1avIAvBdq-QV2tNbOn9
"""


# from google.colab import drive
# drive.mount('/content/drive')


# %cd /content/drive/MyDrive/

import pandas as pd

df_steam = pd.read_csv('./data/final_seh2.csv')
df_steam.head()

df_steam=df_steam.drop(columns=['Unnamed: 0','Unnamed: 0.1'])

df_steam=df_steam.dropna(axis=0)

df_steam=df_steam.reset_index()

df_steam=df_steam.drop(columns='index')

df_steam.head()

df_steam = df_steam.rename(
    columns={
        "steamid": "user",
          
    }
)

df_meta = pd.read_csv('./data/joined_meta_df.csv')
df_meta.head()

df_meta=df_meta.drop(columns='Unnamed: 0')

df_meta.info()

df_meta=df_meta.dropna(axis=0)

df_meta.info()

df_meta['title'] = df_meta['title'].str.replace("[^A-Za-z0-9]+","")
df_meta['title'] = df_meta['title'].str.upper()

df_meta= df_meta[df_meta['title'] != '']

df_meta.head()

df_meta.info()

df_meta = df_meta.rename(
    columns={
        "username": "user",
          
    }
)

review_per_meta = pd.DataFrame(df_meta['user'].value_counts())
review_per_meta = review_per_meta.reset_index().rename(columns={'index':'user', 'user':'counts'})
review_per_meta.head()

review_per_meta2=review_per_meta[review_per_meta['counts']>=5] # 유저평가 수가 20개 이상인 데이터만 남김
review_per_meta2.head()

meta_df=pd.merge(df_meta,review_per_meta2,on='user',how='right')
meta_df.head()

meta_df=meta_df.drop(columns='counts', axis=1)
meta_df.head()

review_per_user = pd.DataFrame(df_steam['user'].value_counts())
review_per_user = review_per_user.reset_index().rename(columns={'index':'user', 'user':'counts'})
review_per_user.head()

review_per_user2=review_per_user[review_per_user['counts']>=20] # 유저평가 수가 20개 이상인 데이터만 남김
review_per_user2.head()

df_steam4=pd.merge(df_steam,review_per_user2,on='user',how='right')
df_steam4.head()

df_steam4.info()

df_steam4['appid']=df_steam4['appid'].astype(int)

df_steam4=df_steam4.drop(columns='counts', axis=1)
df_steam4.head()

len(df_steam4['title'].unique())

df_steam4['title'] = df_steam4['title'].str.replace("[^A-Za-z0-9]+","")
df_steam4['title'] = df_steam4['title'].str.upper()

df_steam4= df_steam4[df_steam4['title'] != '']

df_steam4.info()

df_concat=pd.concat([df_steam4,meta_df],join='inner')
df_concat.head()

import pickle

df_concat.to_pickle('steam_meta.pkl') # 데이터가 커서 피클로 저장

