# -*- coding: utf-8 -*-
"""협업 필터링 제출(3)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UhOb0T4h6Gh0uYoXV84F9nsGhNEE4I4X
"""

# Commented out IPython magic to ensure Python compatibility.
## 코랩을 사용할 때
#드라이브 마운트
from google.colab import drive
drive.mount('/content/drive')

#현재 작업 위치 이동
#띄어쓰기에 \붙일 것
# %cd /content/drive/MyDrive/MultiCampus/데이터 시각화3

import pickle
import pandas as pd

similarity_rate2 = pd.read_pickle('gamedata.pkl')# 피클로 저장된 파일 불러오기

def recommend_game(appid, top_n): 
  '''게임추천 모델
  appid: 게임 고유 코드
  top_n: 추천 받을 게임 개수
  '''
  rec_game=similarity_rate2[appid].reset_index()
  rec_game = rec_game.rename(columns={"appid": "game",appid:'similarity'})
  rec_game=rec_game.sort_values(by='similarity',ascending=False).head(top_n)

  return rec_game

# game1, game2, game3 추천 게임 - 유사도 테이블
def gentleman_ver2(game1, game2, game3):
  d1 = pd.DataFrame(recommend_game(game1, top_n=10), columns=['game', 'similarity']) # game1 추천목록 & 유사도
  d2 = pd.DataFrame(recommend_game(game2, top_n=10), columns=['game', 'similarity']) # game2 추천목록 & 유사도
  d3 = pd.DataFrame(recommend_game(game3, top_n=10), columns=['game', 'similarity']) # game3 추천목록 & 유사도
  df = pd.merge(d1, d2, on='game', how='outer') # d1, d2 merge
  df = pd.merge(df, d3, on='game', how='outer') # d2, d3 merge

  for game in df['game']: # ['game'] 행 하나씩 돌면서 
   if game in [game1, game2, game3]: # game이 game1, game2, game3에 해당하는 경우
      drop_index = df[df['game']==game].index
      df.drop(drop_index, axis='index', inplace=True) # 해당 행 drop

  # 추천 리스트 간 중복되는 게임이 없는 경우 각 추천리스트에서 2개씩 뽑음
  if len(df) == 30: 
    return [x for x in  recommend_game(game1, top_n=2)['game'].unique()]+ [x for x in recommend_game(game2, top_n=2)['game'].unique()] 
    + [x for x in recommend_game(game3, top_n=2)['game'].unique()]
  # 유사도 평균 내서 상위 6개 추출
  else : 
    df.fillna(0, inplace=True)
    df['mean'] = df.mean(axis=1, numeric_only=True)
    df.sort_values('mean', ascending=False, inplace=True)
    return list(df['game'][:6])

print(gentleman_ver2(240,3010,1225780))

